name: Automation: Dev

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Which job to run'
        required: true
        type: choice
        options:
          - buyer
          - safari
          - full-regression

jobs:
  buyer:
    name: [R] Buyer Tests
    if: ${{ github.event.inputs.job == 'buyer' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Buyer Tests
        run: echo "Running buyer tests with config.buyer.json"

  safari:
    name: Safari Essential
    if: ${{ github.event.inputs.job == 'safari' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Safari Tests
        run: echo "Running safari tests with config.safari.json"

  full-regression:
    name: Full Regression 🔁
    if: ${{ github.event.inputs.job == 'full-regression' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Full Regression
        run: echo "Running full regression tests with config.full.json"
