name: Run Tests on DEV

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run smoke tests
        run: echo "Running smoke tests on DEV config"

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run integration tests
        run: echo "Running integration tests on DEV config"

  ui:
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run UI tests
        run: echo "Running UI tests on DEV config"
