name: "Automation: Dev"

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Select which test suite to run"
        required: true
        default: "full-regression"
        type: choice
        options:
          - buyer
          - safari
          - full-regression

jobs:
  run-buyer:
    if: ${{ github.event.inputs.target == 'buyer' }}
    name: "Buyer Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run buyer tests
        run: echo "Running buyer tests with config.buyer.json"

  run-safari:
    if: ${{ github.event.inputs.target == 'safari' }}
    name: "Safari Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run safari tests
        run: echo "Running safari tests with config.safari.json"

  run-full:
    if: ${{ github.event.inputs.target == 'full-regression' }}
    name: "Full Regression"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run full regression
        run: echo "Running full regression tests with config.full.json"
